###################################################################

# Created by write_sdc on Fri May 12 08:37:30 2023

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {out_1[15]}]
set_load -pin_load 0.05 [get_ports {out_1[14]}]
set_load -pin_load 0.05 [get_ports {out_1[13]}]
set_load -pin_load 0.05 [get_ports {out_1[12]}]
set_load -pin_load 0.05 [get_ports {out_1[11]}]
set_load -pin_load 0.05 [get_ports {out_1[10]}]
set_load -pin_load 0.05 [get_ports {out_1[9]}]
set_load -pin_load 0.05 [get_ports {out_1[8]}]
set_load -pin_load 0.05 [get_ports {out_1[7]}]
set_load -pin_load 0.05 [get_ports {out_1[6]}]
set_load -pin_load 0.05 [get_ports {out_1[5]}]
set_load -pin_load 0.05 [get_ports {out_1[4]}]
set_load -pin_load 0.05 [get_ports {out_1[3]}]
set_load -pin_load 0.05 [get_ports {out_1[2]}]
set_load -pin_load 0.05 [get_ports {out_1[1]}]
set_load -pin_load 0.05 [get_ports {out_1[0]}]
set_load -pin_load 0.05 [get_ports {out_2[15]}]
set_load -pin_load 0.05 [get_ports {out_2[14]}]
set_load -pin_load 0.05 [get_ports {out_2[13]}]
set_load -pin_load 0.05 [get_ports {out_2[12]}]
set_load -pin_load 0.05 [get_ports {out_2[11]}]
set_load -pin_load 0.05 [get_ports {out_2[10]}]
set_load -pin_load 0.05 [get_ports {out_2[9]}]
set_load -pin_load 0.05 [get_ports {out_2[8]}]
set_load -pin_load 0.05 [get_ports {out_2[7]}]
set_load -pin_load 0.05 [get_ports {out_2[6]}]
set_load -pin_load 0.05 [get_ports {out_2[5]}]
set_load -pin_load 0.05 [get_ports {out_2[4]}]
set_load -pin_load 0.05 [get_ports {out_2[3]}]
set_load -pin_load 0.05 [get_ports {out_2[2]}]
set_load -pin_load 0.05 [get_ports {out_2[1]}]
set_load -pin_load 0.05 [get_ports {out_2[0]}]
set_load -pin_load 0.05 [get_ports {out_3[15]}]
set_load -pin_load 0.05 [get_ports {out_3[14]}]
set_load -pin_load 0.05 [get_ports {out_3[13]}]
set_load -pin_load 0.05 [get_ports {out_3[12]}]
set_load -pin_load 0.05 [get_ports {out_3[11]}]
set_load -pin_load 0.05 [get_ports {out_3[10]}]
set_load -pin_load 0.05 [get_ports {out_3[9]}]
set_load -pin_load 0.05 [get_ports {out_3[8]}]
set_load -pin_load 0.05 [get_ports {out_3[7]}]
set_load -pin_load 0.05 [get_ports {out_3[6]}]
set_load -pin_load 0.05 [get_ports {out_3[5]}]
set_load -pin_load 0.05 [get_ports {out_3[4]}]
set_load -pin_load 0.05 [get_ports {out_3[3]}]
set_load -pin_load 0.05 [get_ports {out_3[2]}]
set_load -pin_load 0.05 [get_ports {out_3[1]}]
set_load -pin_load 0.05 [get_ports {out_3[0]}]
set_load -pin_load 0.05 [get_ports {out_4[15]}]
set_load -pin_load 0.05 [get_ports {out_4[14]}]
set_load -pin_load 0.05 [get_ports {out_4[13]}]
set_load -pin_load 0.05 [get_ports {out_4[12]}]
set_load -pin_load 0.05 [get_ports {out_4[11]}]
set_load -pin_load 0.05 [get_ports {out_4[10]}]
set_load -pin_load 0.05 [get_ports {out_4[9]}]
set_load -pin_load 0.05 [get_ports {out_4[8]}]
set_load -pin_load 0.05 [get_ports {out_4[7]}]
set_load -pin_load 0.05 [get_ports {out_4[6]}]
set_load -pin_load 0.05 [get_ports {out_4[5]}]
set_load -pin_load 0.05 [get_ports {out_4[4]}]
set_load -pin_load 0.05 [get_ports {out_4[3]}]
set_load -pin_load 0.05 [get_ports {out_4[2]}]
set_load -pin_load 0.05 [get_ports {out_4[1]}]
set_load -pin_load 0.05 [get_ports {out_4[0]}]
set_load -pin_load 0.05 [get_ports instruction_fail]
set_ideal_network -no_propagate  [get_ports clk]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  5  [get_ports in_valid]
set_input_delay -clock clk  5  [get_ports {instruction[31]}]
set_input_delay -clock clk  5  [get_ports {instruction[30]}]
set_input_delay -clock clk  5  [get_ports {instruction[29]}]
set_input_delay -clock clk  5  [get_ports {instruction[28]}]
set_input_delay -clock clk  5  [get_ports {instruction[27]}]
set_input_delay -clock clk  5  [get_ports {instruction[26]}]
set_input_delay -clock clk  5  [get_ports {instruction[25]}]
set_input_delay -clock clk  5  [get_ports {instruction[24]}]
set_input_delay -clock clk  5  [get_ports {instruction[23]}]
set_input_delay -clock clk  5  [get_ports {instruction[22]}]
set_input_delay -clock clk  5  [get_ports {instruction[21]}]
set_input_delay -clock clk  5  [get_ports {instruction[20]}]
set_input_delay -clock clk  5  [get_ports {instruction[19]}]
set_input_delay -clock clk  5  [get_ports {instruction[18]}]
set_input_delay -clock clk  5  [get_ports {instruction[17]}]
set_input_delay -clock clk  5  [get_ports {instruction[16]}]
set_input_delay -clock clk  5  [get_ports {instruction[15]}]
set_input_delay -clock clk  5  [get_ports {instruction[14]}]
set_input_delay -clock clk  5  [get_ports {instruction[13]}]
set_input_delay -clock clk  5  [get_ports {instruction[12]}]
set_input_delay -clock clk  5  [get_ports {instruction[11]}]
set_input_delay -clock clk  5  [get_ports {instruction[10]}]
set_input_delay -clock clk  5  [get_ports {instruction[9]}]
set_input_delay -clock clk  5  [get_ports {instruction[8]}]
set_input_delay -clock clk  5  [get_ports {instruction[7]}]
set_input_delay -clock clk  5  [get_ports {instruction[6]}]
set_input_delay -clock clk  5  [get_ports {instruction[5]}]
set_input_delay -clock clk  5  [get_ports {instruction[4]}]
set_input_delay -clock clk  5  [get_ports {instruction[3]}]
set_input_delay -clock clk  5  [get_ports {instruction[2]}]
set_input_delay -clock clk  5  [get_ports {instruction[1]}]
set_input_delay -clock clk  5  [get_ports {instruction[0]}]
set_input_delay -clock clk  5  [get_ports {output_reg[19]}]
set_input_delay -clock clk  5  [get_ports {output_reg[18]}]
set_input_delay -clock clk  5  [get_ports {output_reg[17]}]
set_input_delay -clock clk  5  [get_ports {output_reg[16]}]
set_input_delay -clock clk  5  [get_ports {output_reg[15]}]
set_input_delay -clock clk  5  [get_ports {output_reg[14]}]
set_input_delay -clock clk  5  [get_ports {output_reg[13]}]
set_input_delay -clock clk  5  [get_ports {output_reg[12]}]
set_input_delay -clock clk  5  [get_ports {output_reg[11]}]
set_input_delay -clock clk  5  [get_ports {output_reg[10]}]
set_input_delay -clock clk  5  [get_ports {output_reg[9]}]
set_input_delay -clock clk  5  [get_ports {output_reg[8]}]
set_input_delay -clock clk  5  [get_ports {output_reg[7]}]
set_input_delay -clock clk  5  [get_ports {output_reg[6]}]
set_input_delay -clock clk  5  [get_ports {output_reg[5]}]
set_input_delay -clock clk  5  [get_ports {output_reg[4]}]
set_input_delay -clock clk  5  [get_ports {output_reg[3]}]
set_input_delay -clock clk  5  [get_ports {output_reg[2]}]
set_input_delay -clock clk  5  [get_ports {output_reg[1]}]
set_input_delay -clock clk  5  [get_ports {output_reg[0]}]
set_output_delay -clock clk  5  [get_ports out_valid]
set_output_delay -clock clk  5  [get_ports {out_1[15]}]
set_output_delay -clock clk  5  [get_ports {out_1[14]}]
set_output_delay -clock clk  5  [get_ports {out_1[13]}]
set_output_delay -clock clk  5  [get_ports {out_1[12]}]
set_output_delay -clock clk  5  [get_ports {out_1[11]}]
set_output_delay -clock clk  5  [get_ports {out_1[10]}]
set_output_delay -clock clk  5  [get_ports {out_1[9]}]
set_output_delay -clock clk  5  [get_ports {out_1[8]}]
set_output_delay -clock clk  5  [get_ports {out_1[7]}]
set_output_delay -clock clk  5  [get_ports {out_1[6]}]
set_output_delay -clock clk  5  [get_ports {out_1[5]}]
set_output_delay -clock clk  5  [get_ports {out_1[4]}]
set_output_delay -clock clk  5  [get_ports {out_1[3]}]
set_output_delay -clock clk  5  [get_ports {out_1[2]}]
set_output_delay -clock clk  5  [get_ports {out_1[1]}]
set_output_delay -clock clk  5  [get_ports {out_1[0]}]
set_output_delay -clock clk  5  [get_ports {out_2[15]}]
set_output_delay -clock clk  5  [get_ports {out_2[14]}]
set_output_delay -clock clk  5  [get_ports {out_2[13]}]
set_output_delay -clock clk  5  [get_ports {out_2[12]}]
set_output_delay -clock clk  5  [get_ports {out_2[11]}]
set_output_delay -clock clk  5  [get_ports {out_2[10]}]
set_output_delay -clock clk  5  [get_ports {out_2[9]}]
set_output_delay -clock clk  5  [get_ports {out_2[8]}]
set_output_delay -clock clk  5  [get_ports {out_2[7]}]
set_output_delay -clock clk  5  [get_ports {out_2[6]}]
set_output_delay -clock clk  5  [get_ports {out_2[5]}]
set_output_delay -clock clk  5  [get_ports {out_2[4]}]
set_output_delay -clock clk  5  [get_ports {out_2[3]}]
set_output_delay -clock clk  5  [get_ports {out_2[2]}]
set_output_delay -clock clk  5  [get_ports {out_2[1]}]
set_output_delay -clock clk  5  [get_ports {out_2[0]}]
set_output_delay -clock clk  5  [get_ports {out_3[15]}]
set_output_delay -clock clk  5  [get_ports {out_3[14]}]
set_output_delay -clock clk  5  [get_ports {out_3[13]}]
set_output_delay -clock clk  5  [get_ports {out_3[12]}]
set_output_delay -clock clk  5  [get_ports {out_3[11]}]
set_output_delay -clock clk  5  [get_ports {out_3[10]}]
set_output_delay -clock clk  5  [get_ports {out_3[9]}]
set_output_delay -clock clk  5  [get_ports {out_3[8]}]
set_output_delay -clock clk  5  [get_ports {out_3[7]}]
set_output_delay -clock clk  5  [get_ports {out_3[6]}]
set_output_delay -clock clk  5  [get_ports {out_3[5]}]
set_output_delay -clock clk  5  [get_ports {out_3[4]}]
set_output_delay -clock clk  5  [get_ports {out_3[3]}]
set_output_delay -clock clk  5  [get_ports {out_3[2]}]
set_output_delay -clock clk  5  [get_ports {out_3[1]}]
set_output_delay -clock clk  5  [get_ports {out_3[0]}]
set_output_delay -clock clk  5  [get_ports {out_4[15]}]
set_output_delay -clock clk  5  [get_ports {out_4[14]}]
set_output_delay -clock clk  5  [get_ports {out_4[13]}]
set_output_delay -clock clk  5  [get_ports {out_4[12]}]
set_output_delay -clock clk  5  [get_ports {out_4[11]}]
set_output_delay -clock clk  5  [get_ports {out_4[10]}]
set_output_delay -clock clk  5  [get_ports {out_4[9]}]
set_output_delay -clock clk  5  [get_ports {out_4[8]}]
set_output_delay -clock clk  5  [get_ports {out_4[7]}]
set_output_delay -clock clk  5  [get_ports {out_4[6]}]
set_output_delay -clock clk  5  [get_ports {out_4[5]}]
set_output_delay -clock clk  5  [get_ports {out_4[4]}]
set_output_delay -clock clk  5  [get_ports {out_4[3]}]
set_output_delay -clock clk  5  [get_ports {out_4[2]}]
set_output_delay -clock clk  5  [get_ports {out_4[1]}]
set_output_delay -clock clk  5  [get_ports {out_4[0]}]
set_output_delay -clock clk  5  [get_ports instruction_fail]
